POST {{base_url}}/openai/v1/chat/completions
Authorization: Bearer {{apikey}}
Content-Type: application/json

{"messages": [{"role": "user", "content": "Can you tell me the current weather in Bogota, Columbia?"}], "model": "llama3-8b-8192"}